fix(mount_matrix): Update gyro matrices
ShadowBlip/InputPlumber pull request #220
Opened 2024-10-19 02:23 UTC by uejji

WIP.  Still gathering device data.

2024-10-22 21:10 UTC, uejji commented
Per discussion with @pastaq, this is a step towards bringing InputPlumber's gyro output in line with that of Steam Deck.

2024-10-24 15:40 UTC, pastaq commented
I'll test this on some of the remaining devices this weekend.

2024-10-24 15:54 UTC, uejji commented
Please feel free to doublecheck my submissions, too.

For reference I've attached an image to illustrate which rotations produce positive and negative deflection values on Steam Deck.  Follow the marked arrow (eg clockwise yaw produces positive values).

![Untitled](https://github.com/user-attachments/assets/21f68c0f-71bb-4665-9c78-135de35e232e)

2024-11-04 03:49 UTC, pastaq requested changes
I was able to test the following devices:
AYANEO 2021
AYANEO 2
AYANEO AIR
AYANEO AIR Plus
AYN Loki Max

I tried to test the AYANEO Next Lite but it was behaving very strangely and I wasn't able to get a valid test out of it. Similarly I need to reinstall the OS on my OrangePi Neo as its currently stuck on a broken version. I'll be unavailable for about 2 weeks if anyone else wants to provide feedback for the remaining devices.

I'd like to double check again that the axes in your last comment are correct for positive/negative values. The animations feel backwards for the first and second axes when the correct matrix is applies to render positive/negative values as described in it.

2024-11-04 03:49 UTC, pastaq commented on rootfs/usr/share/inputplumber/devices/50-ayaneo_2021.yaml
> +        y: [1, 0, 0]
Based on your diagram of positive/negative deflection, this should be inverted.
```suggestion
        y: [-1, 0, 0]
```

2024-11-04 03:49 UTC, pastaq commented on rootfs/usr/share/inputplumber/devices/50-ayn_loki_max.yaml
> +        x: [-1, 0, 0]
Based on your diagram of positive/negative deflection, these should be inverted.
```suggestion
        x: [1, 0, 0]
```

2024-11-04 03:49 UTC, pastaq commented on rootfs/usr/share/inputplumber/devices/50-ayn_loki_max.yaml
> +        z: [0, 0, 1]
```suggestion
        z: [0, 0, -1]
```

2024-11-04 13:50 UTC, uejji commented
This isn't the best example, but I think it can help if reviewed at 0.5x speed:
https://youtu.be/1TL8WtX_IXs?t=80

This video at the marked timestamp shows which rotations on the Steam Deck produce positive or negative deflection values for the first two axes.

I struggle to find an accurate and well-communicated method of describing these rotations other than the image provided in the previous comment, but I would definitely welcome any other descriptions.

If your corrections correlate to the rotations and deflection values shown in the video, then they are correct.

2024-11-04 19:34 UTC, pastaq commented
Okay, seems we're on the same page then.

I'll finish testing the remaining devices later this month. Thanks.

2024-11-06 02:57 UTC, uejji commented
Thanks to:
@pastaq for providing gyro testing on Air, 2021 and Loki Max
@winghugs for providing gyro testing on Air 1S 8840U

2024-11-21 21:49 UTC, pastaq commented
I should have some time this weekend to verify on the following devices:
AYANEO Flip KB
Legion Go
AYANEO 2S
OrangePi Neo
AYANEO Next Lite

That should cover the majority of devices people are using. It would be nice to get an Loki Zero and Loki Mini Pro, air plus mendo before this is merged. I'm comfortable with the win4, air 1s as they are tested on at leas t one CPU. Claw I'm not worries about as that hasn't been confirmed working yet anyway.

2024-11-21 22:23 UTC, uejji commented
> Loki Zero and Loki Mini Pro, air plus mendo

No idea if I'll be able to get access to any of those, but I'll update if someone with one turns up.

2024-11-22 21:08 UTC, fewtarius commented
> I should have some time this weekend to verify on the following devices: AYANEO Flip KB Legion Go AYANEO 2S OrangePi Neo AYANEO Next Lite
> 
> That should cover the majority of devices people are using. It would be nice to get an Loki Zero and Loki Mini Pro, air plus mendo before this is merged. I'm comfortable with the win4, air 1s as they are tested on at leas t one CPU. Claw I'm not worries about as that hasn't been confirmed working yet anyway.

We spent some time today on the Flip KB and 2S to make sure they behave correctly. :)

2024-12-13 22:01 UTC, uejji commented
Tested successfully on Flip DS

2024-12-18 00:33 UTC, pastaq approved these changes
I think this is well baked. Any issues can be solved in a bug fix.

2024-12-18 04:54 UTC, uejji commented
Resolves https://github.com/ShadowBlip/InputPlumber/issues/217

2024-12-20 02:39 UTC, merged