Implement LED source output device
ShadowBlip/InputPlumber pull request #246
Opened 2024-12-31 02:47 UTC by NeroReflex

Implement LED source output device contextually a code cleanup:
  - Remove duplicated code
  - Avoid spawning useless tasks
  - Keep references to some spwned tasks and join then in the main() function
  - Avoid calling a CLI software to fetch devices data and use the (already in use) udev crate
  -  Add VSCode launch.json file to be able to remote debug the software

2024-12-31 10:10 UTC, pastaq requested changes
I left a few comments but I'll add some more general notes here. I haven't given everything in the PR a completely thorough look due to some of the reasons posted below.

1.) I'm not a fan of sweeping refactoring that also includes new features as it is difficult to both review and test. I would prefer one PR to add LED RGB and one PR to refactor manager/devnode usage. Order isn't super important but I think it would be easier to refactor then add new features after.

2.) Please explain some of the reasons behind many of the changes. With so many very large changes it is difficult to grasp the context without having discussions beforehand or adding lots of reasoning in the pull request itself.

3.) Please ensure all commit titles are using the semantics format so our CI will pick everything up properly.

2024-12-31 10:10 UTC, pastaq commented on src/udev/mod.rs
This is an interface that predates our use of udev-rs and is being depreciated over time. I don't know if there is value in updating it vice removing it and using the newer udev methods.

2024-12-31 16:37 UTC, NeroReflex commented
> I left a few comments but I'll add some more general notes here. I haven't given everything in the PR a completely thorough look due to some of the reasons posted below.
> 
> 1.) I'm not a fan of sweeping refactoring that also includes new features as it is difficult to both review and test. I would prefer one PR to add LED RGB and one PR to refactor manager/devnode usage. Order isn't super important but I think it would be easier to refactor then add new features after.
> 
> 2.) Please explain some of the reasons behind many of the changes. With so many very large changes it is difficult to grasp the context without having discussions beforehand or adding lots of reasoning in the pull request itself.
> 
> 3.) Please ensure all commit titles are using the semantics format so our CI will pick everything up properly.

1) the PR is divided in two stages: early commits are refactors that are needed to avoid losing referemces to spawned threads, then there is the commit that adds leds code and remove useless specialization of source devices creation: as a result of that removal leds are also being taken into consideration. Previous code was very long spanning multiple monitora is length and adding another specialization was both unpractical and basically more tech debt.

2) well see 1, I can write that to commit messages if you like that more

3) what? Where do I read about that?

2024-12-31 16:39 UTC, NeroReflex commented on src/input/manager.rs
See general answer. Basically reduce reliance of devnode() as leds don't have one, while also removing duplicated code with very minimal specialization

2024-12-31 16:40 UTC, NeroReflex commented on src/input/manager.rs
> +            // Watch for iio and other devices
When I refactored this method I kept the logic intact. This question is one I cannot answer.

2024-12-31 16:41 UTC, NeroReflex commented on src/input/manager.rs
> +        let this: &Self = self;
Self is mutable. Is used to make the borrow checker happy...

2024-12-31 16:44 UTC, NeroReflex commented on src/input/source/led/multicolor_chassis.rs
The way it's implemented is easy to extend to more devices. It scan multi_index and creates a map of component. If a component is recognised (currently only rgb is) when a color arrives it reads the multi_intensity file and changes only relevant and recognised values. There is no way to specialize this when just multi_index contains different count or rgb or rgba.

2024-12-31 16:45 UTC, NeroReflex commented on src/config/mod.rs
> +    pub b: u8,
Yes, I can do that. An Option<u8> for alpha

2024-12-31 17:01 UTC, NeroReflex commented on src/input/manager.rs
> +            // Watch for iio and other devices
I re-watched the code: discover_all_devices does the first initialization, while watch_iio_devices is meant to keep living on.

Before the refactor discover_all_devices was spawned in a task and that tash's reference was lost.

2024-12-31 17:02 UTC, NeroReflex commented on src/input/manager.rs
> +        let this: &Self = self;
well.... I solved this.

2024-12-31 17:03 UTC, NeroReflex commented on src/dbus/interface/source/led.rs
> +/// DBusInterface exposing information about a HIDRaw device
well I copied it from iio, so it is wrong in IIO too. lol.

2024-12-31 17:07 UTC, NeroReflex commented on src/config/mod.rs
> +    /// Returns true if a given iio device is within a list of iio configs.
fixed

2024-12-31 17:09 UTC, NeroReflex commented on src/dbus/interface/source/led.rs
> +    /// Creates a new instance of the source hidraw interface on DBus. Returns
same as before: iio is also wrong.

2024-12-31 17:15 UTC, NeroReflex commented on src/udev/mod.rs
> This is an interface that predates our use of udev-rs and is being depreciated over time. I don't know if there is value in updating it vice removing it and using the newer udev methods.

I think there is value in that: if it is kept as small as possible it will reflect the bare minimum needed for the software to run and allows for future ways of discovering devices.

2024-12-31 21:44 UTC, NeroReflex commented on src/drivers/opineo/driver.rs
> +                "Device '{}' does not have a devnode: a valid OrangePi NEO Controller has one",
I want the message to include the fact it's coming from an opi device... Can you give me a phrase that includes that?

2024-12-31 23:13 UTC, pastaq commented on src/drivers/opineo/driver.rs
> +                "Device '{}' does not have a devnode: a valid OrangePi NEO Controller has one",
"Failed to find device node for {}, aborting initialization as OrangePi NEO Controller."

2024-12-31 23:17 UTC, pastaq commented on src/input/manager.rs
> +            // Watch for iio and other devices
The code highlight was unfortunate and led you to check something I didn't intend. The comment  for line 422 and the comment for line 444 `Self::watch_hidraw_devices(cmd_tx_hidraw, &mut watcher_rx),` are strange. will watch_hidraw_devices watch for iio? I know that both are in /dev so it's possible?

2025-01-02 06:44 UTC, flukejones commented on src/input/composite_device/mod.rs
> +                            log::error!("Failed to process event: {}", e.to_string());
All of this is unnecessary and adds noise to the commit series. These types of things should be done as a completely separate "cleanup" series, probably using clippy also.

2025-01-02 06:54 UTC, flukejones commented on src/udev/device.rs
> +        match s.ends_with("/device") {
Is this actually the correct thing to do? In changes below you change from this:
```rust
        let path = format!("/sys{}/device/id/vendor", self.path.clone());
```
to this:
```rust
        let path = format!("{}/id/vendor", self.sysnode_device_link());
```
The path now has `device` appended to it since it didn't end with it. Only `get_parent_device_name()` expected this.

I would suggest adding some unit tests. Or drop this change completely since the commit apparently addresses only the `u64 change and not this.

In fact please drop all the changes that aren't `u64`. You've changed the behaviour unnecessarily

2025-01-02 07:02 UTC, flukejones commented on src/udev/mod.rs
You really want to not use `Command::new("udevadm")` in these things unless there is no other way. I would suggest full removal

2025-01-02 07:03 UTC, flukejones commented on src/udev/mod.rs
> +                nix::libc::S_IFBLK => Some(udev::DeviceType::Block),
It's likely to be preferable to use the `rustix` crate instead of nix in most cases now.

2025-01-02 07:21 UTC, flukejones commented on src/config/mod.rs
> +        if let Some(name) = evdev_config.name.as_ref() {
can also be done as
```rust
        if let Some(name) = &evdev_config.name {
```
which is more concise. Keep in mind that this change isn't required at all, since `String` is clone and not copy, the string is moved to here and ownership taken, then the `.as_str()` is called below to get a str ref.

Personally I would drop these changes from the commit to reduce noise.

2025-01-02 07:25 UTC, flukejones commented on src/dbus/interface/source/led.rs
> +        tokio::task::spawn(async move {
This is done in an async function, is it *really* required just to start the object server? The `zbus` crate starts async tasks itself, see https://github.com/dbus2/zbus/blob/71834a41a008214acda27b31dc5948c8ca08a594/zbus/src/connection/mod.rs#L950

2025-01-02 19:37 UTC, ShadowApex requested changes

2025-01-02 19:37 UTC, ShadowApex commented on src/input/composite_device/mod.rs
> +                )
If the error already implements the `Display` trait, then you can just include the variable in the format string to do the equivalent:
```suggestion
                return Err(format!(
                    "Failed to set composite device for target device: {e}"
                )
```

2025-01-02 19:37 UTC, ShadowApex commented on src/input/composite_device/mod.rs
> +        let dev_subsystem = (&device).subsystem();
this expression borrows a value the compiler would automatically borrow
```suggestion
        let dev_name = device.name();
        let dev_subsystem = device.subsystem();
```

2025-01-02 19:37 UTC, ShadowApex commented on src/input/composite_device/mod.rs
> +                    .map_or(None, |cfg| cfg.iio);
```suggestion
                let config = self
                    .config
                    .get_matching_device(&device)
                    .and_then(|cfg| cfg.iio);
```

2025-01-02 19:37 UTC, ShadowApex commented on src/input/composite_device/mod.rs
> +                    .map_or(None, |cfg| cfg.led);
```suggestion
                let config = self
                    .config
                    .get_matching_device(&device)
                    .and_then(|cfg| cfg.led);
```

2025-01-02 19:37 UTC, ShadowApex commented on src/input/manager.rs
> +                );
With the removal of the second loop, how will new composite devices be created in these circumstances? The expected behavior should be:
- If a device matches an existing composite device, and it hasn't reached its maximum number of source devices, it should be added to the existing composite device.
- If a device matches an existing composite device, but it HAS reached its maximum, a new composite device should be created.
- Lastly, if no existing composite device exists, a new one should be created.

With these changes, I don't see how a new composite device could be ever be created if an existing one reaches its max.

2025-01-02 19:50 UTC, ShadowApex commented on src/input/manager.rs
> +                );
For example, you can follow these steps to see this problem manifested:

- Enable management of all supported input devices: `busctl set-property org.shadowblip.InputPlumber /org/shadowblip/InputPlumber/Manager org.shadowblip.InputManager ManageAllDevices b 1`
- Plug in an XBox 360 controller (or other supported external controller). A Composite Device should be created for that controller.
- Plug in a second controller of the same type. A second Composite Device should be created for that second controller.

2025-01-02 19:56 UTC, pastaq commented on src/udev/device.rs
> +        match s.ends_with("/device") {
Agree, only the bugfix is needed here.

2025-01-02 19:58 UTC, pastaq commented on src/input/manager.rs
> +            log::warn!(
This is going to be very noisy. Use trace, or at most debug.

2025-01-02 20:00 UTC, pastaq commented on src/config/mod.rs
> +    pub b: u8,
I think some provide a duty cycle to change the overall brightness.

2025-01-02 20:14 UTC, pastaq requested changes
I would drop these commits:

cd3dbdd9bc9b822ae6b2d7c6cfe9255655797618 
53edb302463419bd3d7fad7bac2d4428d13c66f6
bbee9b3ca79cb54e28be046300e26c7cbd3de69d

I would cherry pick these commits into a separate cleanup PR and drop them from this one:
005be0023880ae3e04cd33d4c9f95419780bbe6c
7135d069010cb501b4904cd108cdd33c7fb1727d
27f33ecc438faec0961396a4a9319ff35872ca96
54db7ae2c70af10e1fe4bdeead40c611075107a8
45d1cdf5a9e21548bc452926e5840aff8f18644b
45eb7117f0e2f8a9bc09ed960daebe1b92baaa6b
c65effe9d7e15e65e683b9d6c9d6adb34fc2c271
0b79670db7007fd9e99d2b53236a05792d25f0a9

2025-01-02 21:05 UTC, NeroReflex commented on src/dbus/interface/source/led.rs
> +        tokio::task::spawn(async move {
> This is done in an async function, is it _really_ required just to start the object server? The `zbus` crate starts async tasks itself, see https://github.com/dbus2/zbus/blob/71834a41a008214acda27b31dc5948c8ca08a594/zbus/src/connection/mod.rs#L950

I copied this code from iio_imu and I mantained like that for consistency. The main problem is that right now listen_on_dbus() the function that contains the spawn is called by manager.rs in a function that must not terminate an the spawned function has a ```rust
conn.object_server().at(path.clone(), iface).await
```

so either more manager.rs logic is changed or that will have to stay like that, unless the await immediatly returns (I assume it won't, but I can try)...

2025-01-02 21:43 UTC, NeroReflex commented on src/udev/mod.rs
> You really want to not use `Command::new("udevadm")` in these things unless there is no other way. I would suggest full removal

See your answer here: https://github.com/ShadowBlip/InputPlumber/pull/246#discussion_r1900584039

Other changes are to cope well with the removal of calling udevadm so you three have to decide if that class has to be:
- fixed and I have to find some other way to implement leds (there might be one that will be more complex, will that be fine?): might be major work for me
- left bugged (it's rare, who cares lol) and call udevadm and not touch that code at all: remove noise from the PR
- pick all changes and futher rework that struct to make it relevant again: maybe needless work as UdevDevice is used way more anyway
- drop that udev::Device structure completely and only use UdevDevice: probably better, but still adds noise so I will do in a separate PR

2025-01-02 21:47 UTC, NeroReflex commented on .vscode/launch.json
> +}
> We shouldn't commit editor-specific configurations

This is not editor configuration as in "dev favourite color palette" this is what is needed to remote debug it. The PATH env var is important too as it specify where to find udevadm.

2025-01-02 21:48 UTC, NeroReflex commented on src/input/manager.rs
> +    ) -> () {
> 

pastaq said otherwise in another comment....

2025-01-02 21:49 UTC, NeroReflex commented on src/input/manager.rs
> +        Manager::discover_devices(&cmd_tx, led_devices).await?;
A leftover from a previous cleanup. I will solve this in the new PR

2025-01-29 12:49 UTC, NeroReflex commented
Superceeded by #268

2025-01-29 12:49 UTC, closed without merging