fix(CompositeDevice): Ensure proper handling of chord events in a way steam can understand them.
ShadowBlip/InputPlumber pull request #32
Opened 2024-04-01 05:43 UTC by pastaq

- Add default configuration for steam that covers 99% of handhelds.

2024-04-01 09:05 UTC, ShadowApex requested changes
The main issue I see with the current implementation is that the `sleep` calls that happen when performing these chords will halt the processing of all events for the CompositeDevice while its sleeping.

To avoid this, I propose we actually spawn a tokio task that will sleep for the desired amount of time, then send a `Command` using the sender side of the CompositeDevice channel to tell the device it should process the event after the sleep has finished.

e.g.

```rust
pub enum Command {
    ...
    WriteEvent(NativeEvent),
...
```

```rust
...
tokio::spawn(async move {
    tokio::time::sleep(Duration::from_millis(80)).await;
    if let Err(e) = tx.send(Command::WriteEvent(event)) {
        log::error!("Failed to send chord event command: {:?}", e);
    }
});
...
```

Then in the run loop, we can process the command sent through the channel after the delay:

```rust
match cmd {
    ...
    Command::WriteEvent(event) => {
        if let Err(e) = self.write_event(event).await {
            log::error!("Failed to write event: {:?}", e);
        }
    }
...
```

2024-04-01 09:16 UTC, ShadowApex commented on src/input/composite_device/mod.rs
> +        let events = self.process_event_list(&event, events);
```suggestion
        // Translate the event using the device profile.
        let is_pressed = event.pressed();
        let mut events = if self.device_profile.is_some() {
            self.translate_event(&event).await?
        } else {
            vec![event]
        };

        // Check if we need to reverse the event list.
        if events.len() > 1 && is_pressed {
            events = events.into_iter().rev().collect();
        }
```

2024-04-01 20:52 UTC, pastaq commented on src/input/composite_device/mod.rs
> +                    sleep(Duration::from_millis(80));
I tried this, the tokio sleeps don't affect the thread we need to sleep so everything breaks.

2024-04-02 00:19 UTC, ShadowApex approved these changes
Ship it!

2024-04-02 00:19 UTC, merged