fix(CompositeDevice): Properly clear BMI source device command queue.
ShadowBlip/InputPlumber pull request #61
Opened 2024-04-26 04:48 UTC by pastaq

- Adds buffer reading to BMI IIO deivce to ensure the command queue doesn't overflow and hand the driver.
- Uses try_send instead of send().await to ensure an improperly implemented driver cannot block the main thread.

2024-04-26 04:48 UTC, pastaq commented
Solves #60

2024-04-27 01:35 UTC, ShadowApex requested changes

2024-04-27 01:35 UTC, ShadowApex commented on src/input/source/iio/bmi_imu.rs
> +                    let duration = time::Duration::from_millis(40);
Do we want to change this back to 250µs? In the future, we can get this from the driver interface based on polling frequency.

2024-04-27 02:09 UTC, ShadowApex approved these changes

2024-04-27 02:10 UTC, merged